### ISSUE TITLE
problem with jack configuration script

### ISSUE THREAD

**Issue by moonshaadow** [Houston4444/RaySession#102]
_Ubuntu studio 18.04
RaySession 0.10.1, recent built_

creating a session with jack config template, then closing it.

No jack config restoration when reoppening the session.

![raysession_jack](https://user-images.githubusercontent.com/29754932/101067311-b05ab300-3597-11eb-9b1c-f58a21b190fd.png)

The script doesn't seem to work.
Here the log :
```
studio@studio-Dell:~$ raysession
QApplication: invalid style override passed, ignoring it.
[ray-daemon]GUI connected at osc.udp://studio-Dell:15797/
[ray-daemon]URL : osc.udp://192.168.0.10:16187/
[ray-daemon]      osc.udp://studio-Dell:16187/
[ray-daemon]ROOT: /home/studio/Librairie/Ray Sessions
[ray-daemon]Attempting to open /home/studio/Librairie/Ray Sessions/jack1
[ray-daemon]Commanding smart clients to switch

[ray-daemon load.sh script]
- Ouverture de la session 'jack1' -
waiting announce from JACK Patch Memory (patch)...
  JACK Patch Memory (patch): lancé

[ray-daemon]Process has pid: 3098
[ray-daemon]The client "JACK Connections" at "osc.udp://127.0.0.1:17327/" informs us it's ready to receive commands.

[ray-daemon load.sh script]
  JACK Connections (patch): announced
attente du chargement de projet de JACK Connections (patch)...

[ray-daemon]patch sends clean

[ray-daemon]Telling all clients that session is loaded...
[ray-daemon]Telling client JACK Connections that session is loaded.
[ray-daemon]Loaded

[ray-daemon load.sh script]
  JACK Connections (patch): projet chargé
la session'jack1' est chargée.

[ray-daemon]Telling JACK Connections to save

[ray-daemon save.sh script]
- Sauvegarde de la session 'jack1' -
en attente de JACK Connections (patch) pour enregistrer ...

[ray-daemon]patch sends clean
[ray-daemon]Session jack1 saved.

[ray-daemon save.sh script]
  JACK Connections (patch): sauvegardé
La session 'jack1' a été sauvegardée.

[ray-daemon-git init]
Dépôt Git vide initialisé dans /home/studio/Librairie/Ray Sessions/jack1/.ray-snapshots/

[ray-daemon-git add -A -v]
add 'jack1.patch.xml'
add 'jack_parameters'
add 'ray-scripts/.directory'
add 'ray-scripts/.jack_config_script'
add 'ray-scripts/close.sh'
add 'ray-scripts/load.sh'
add 'ray-scripts/save.sh'
add 'raysession.xml'

[ray-daemon-git commit -m ray]
[master (commit racine) e889fa6] ray
 8 files changed, 173 insertions(+)
 create mode 100644 jack1.patch.xml
 create mode 100644 jack_parameters
 create mode 100644 ray-scripts/.directory
 create mode 100644 ray-scripts/.jack_config_script
 create mode 100755 ray-scripts/close.sh
 create mode 100755 ray-scripts/load.sh
 create mode 100755 ray-scripts/save.sh
 create mode 100644 raysession.xml

[ray-daemon close.sh script]
attente de la fermeture de JACK Connections (patch)...
  JACK Connections (patch): arrêt
  JACK Connections (patch): terminé par instruction du serveur

[ray-daemon]Done
[ray-daemon]Bye Bye...
studio@studio-Dell:~$ 
```

**Comment by Houston4444** [comment]
Ah. Que répondent les commandes `aplay` et `arecord`, et qu'y a-t-il dans le fichier jack_parameters de la session ?
Merci du rapport !

**Comment by moonshaadow** [comment]
Hello @Houston4444 !
Désolé pour le délai ...

```
~$ aplay -l
**** Liste des Périphériques Matériels PLAYBACK ****
carte 0: PCH [HDA Intel PCH], périphérique 0: ALC269VB Analog [ALC269VB Analog]
  Sous-périphériques: 0/1
  Sous-périphérique #0: subdevice #0
carte 1: HDMI [HDA ATI HDMI], périphérique 3: HDMI 0 [HDMI 0]
  Sous-périphériques: 1/1
  Sous-périphérique #0: subdevice #0
```
```
~$ arecord -l
**** Liste des Périphériques Matériels CAPTURE ****
carte 0: PCH [HDA Intel PCH], périphérique 0: ALC269VB Analog [ALC269VB Analog]
  Sous-périphériques: 0/1
  Sous-périphérique #0: subdevice #0

```

Fichier jack_parameters :

```
hostname:studio-Dell
jack_started:1
/engine/driver:alsa
/engine/realtime:1
/engine/verbose:0
/engine/client-timeout:500
/driver/device:hw:0
/driver/capture:none
/driver/playback:none
/driver/rate:48000
/driver/period:512
/driver/nperiods:2
/driver/hwmon:0
/driver/hwmeter:0
/driver/duplex:1
/driver/softmode:0
/driver/monitor:0
/driver/dither:n
/driver/shorts:0
```
A noter que j'utilise `cadence` pour configurer jack, et que le bug se reproduit uniquement si capture ou playback est configuré sur "none". Cette valeur "none" n'est pas possible avec `qjackctl`

A noter également que si je change la valeur de `/driver/capture` et `/driver/playback` via cadence, que je redémarre jack (toujours via cadence)  et que je créé et sauvegarde une nouvelle ray-session, les valeurs sauvées pour playback et capture sont celles d'avant le redémarrage de jack. Pourtant cadence semble bien faire son taf en sauvant les paramètres dans `~/.config/jack/conf.xml`. La faute à `ray-jack_checker_daemon` peut-être ?

Voici ce qu'il me dit quand je redémarre jack :
```

~$ ray-jack_checker_daemon --force-reliable
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/bin/ray-jack_checker_daemon", line 48, in dbus_signal_receiver
    write_the_file(jack_started=jack_status)
  File "/usr/local/bin/ray-jack_checker_daemon", line 63, in write_the_file
    params = configure_iface.GetParametersInfo(['engine'])
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.145 was not provided by any .service files
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/bin/ray-jack_checker_daemon", line 48, in dbus_signal_receiver
    write_the_file(jack_started=jack_status)
  File "/usr/local/bin/ray-jack_checker_daemon", line 63, in write_the_file
    params = configure_iface.GetParametersInfo(['engine'])
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.145 was not provided by any .service files
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/bin/ray-jack_checker_daemon", line 48, in dbus_signal_receiver
    write_the_file(jack_started=jack_status)
  File "/usr/local/bin/ray-jack_checker_daemon", line 63, in write_the_file
    params = configure_iface.GetParametersInfo(['engine'])
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.145 was not provided by any .service files
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/bin/ray-jack_checker_daemon", line 48, in dbus_signal_receiver
    write_the_file(jack_started=jack_status)
  File "/usr/local/bin/ray-jack_checker_daemon", line 63, in write_the_file
    params = configure_iface.GetParametersInfo(['engine'])
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.145 was not provided by any .service files
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/bin/ray-jack_checker_daemon", line 48, in dbus_signal_receiver
    write_the_file(jack_started=jack_status)
  File "/usr/local/bin/ray-jack_checker_daemon", line 63, in write_the_file
    params = configure_iface.GetParametersInfo(['engine'])
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.145 was not provided by any .service files
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/bin/ray-jack_checker_daemon", line 48, in dbus_signal_receiver
    write_the_file(jack_started=jack_status)
  File "/usr/local/bin/ray-jack_checker_daemon", line 63, in write_the_file
    params = configure_iface.GetParametersInfo(['engine'])
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.145 was not provided by any .service files
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/bin/ray-jack_checker_daemon", line 48, in dbus_signal_receiver
    write_the_file(jack_started=jack_status)
  File "/usr/local/bin/ray-jack_checker_daemon", line 63, in write_the_file
    params = configure_iface.GetParametersInfo(['engine'])
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.145 was not provided by any .service files
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/bin/ray-jack_checker_daemon", line 48, in dbus_signal_receiver
    write_the_file(jack_started=jack_status)
  File "/usr/local/bin/ray-jack_checker_daemon", line 63, in write_the_file
    params = configure_iface.GetParametersInfo(['engine'])
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.145 was not provided by any .service files
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/bin/ray-jack_checker_daemon", line 48, in dbus_signal_receiver
    write_the_file(jack_started=jack_status)
  File "/usr/local/bin/ray-jack_checker_daemon", line 63, in write_the_file
    params = configure_iface.GetParametersInfo(['engine'])
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.145 was not provided by any .service files
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/local/bin/ray-jack_checker_daemon", line 48, in dbus_signal_receiver
    write_the_file(jack_started=jack_status)
  File "/usr/local/bin/ray-jack_checker_daemon", line 63, in write_the_file
    params = configure_iface.GetParametersInfo(['engine'])
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.145 was not provided by any .service files
```

**Comment by Houston4444** [comment]
Salut ! Merci.
Pour le bug initial, ça ne me paraît pas compliqué à corriger, je regarde ça sous peu, je n'ai pas dû penser au fait qu'on puisse utiliser JACK sans entrées ou sans sorties matérielles.

Pour l'autre bug, c'est assez étrange, mais il n'est pas exclu que ça vienne d'une incompatibilité entre le ray-jack_checker_daemon et studio control, ou entre studio control et le jack dbus.
J'ai essayé il n'y a pas très longtemps ubuntu studio, j'avais constaté que le script de mémoire de configuration de JACK pour raysession ne pouvait pas y fonctionner étant donné que même jack_control ne répond pas correctement au statut de JACK (démarré, arrêté), et jack_control interroge jack_dbus.

J'ai l'impression que ce que dit ray-jack_checker_daemon dans le message, ça veut dire: je ne trouve pas le service dbus de JACK.

**Comment by moonshaadow** [comment]
En fait pour le second bug, je viens de me rendre compte que c'est du à ma mauvaise utilisation de cadence : j'avais pris l'habitude, dans l'interface graphique, d'utiliser la fonction Force Restart après avoir changer des paramètres. Du coup une fois fait ça, ton script n'arrive plus à redémarrer jack, enfin pas tout le temps on dirait. 
Si j'utilise simplement Start et Stop pour faire mes tests, le script a l'air de fonctionner.

**Comment by Houston4444** [comment]
Salut. Le premier bug doit être résolu, peux-tu essayer ?

**Comment by moonshaadow** [comment]
Salut !
C'est résolu, oui. Merci!
En tout cas c'est un script qui peut être vraiment utile. Et c'est fluide, rapide. Au top!

**Comment by Houston4444** [comment]
Merci pour le retour ! Je ferme cette issue du coup.
