### ISSUE TITLE
I can´t open RaySession: ModuleNotFoundError: No module named 'PyQt5.QtSvg'

### ISSUE THREAD

**Issue by gilfuser** [Houston4444/RaySession#143]
Hi. Thank you for this great app.

Im using linux Pop! OS, an Ubuntu flavor, 21.10. I just installed RaySession, but I'm not able to open it. When I try it through cmd line I get this:
```
Traceback (most recent call last):
  File "/usr/local/share/raysession/src/bin/raysession", line 14, in <module>
    from gui_session import SignaledSession
  File "/usr/local/share/raysession/src/gui/gui_session.py", line 8, in <module>
    from patchcanvas import patchcanvas
  File "/usr/local/share/raysession/src/gui/patchcanvas/patchcanvas.py", line 56, in <module>
    from .canvasbox import CanvasBox
  File "/usr/local/share/raysession/src/gui/patchcanvas/canvasbox.py", line 77, in <module>
    from .canvasicon import CanvasSvgIcon, CanvasIconPixmap
  File "/usr/local/share/raysession/src/gui/patchcanvas/canvasicon.py", line 26, in <module>
    from PyQt5.QtSvg import QGraphicsSvgItem, QSvgRenderer
ModuleNotFoundError: No module named 'PyQt5.QtSvg'
```

Is it something missing in my system? I do have `libqt5svg5-dev` installed.

best regards,
Gil

**Comment by Houston4444** [comment]
Hi.

On debian the needed package is python3-pyqt5.qtsvg . It is probably the same on Ubuntu.

Best regards.
Mathieu

**Comment by gilfuser** [comment]
I just checked it and I already have it.

**Comment by Houston4444** [comment]
I don't know what to say, the message clearly says that the module is missing. Maybe try to purge and re-install the package. It's a shame, qtsvg is only used for hardware and pulseaudio/pipewire boxes icons in the patchbay.

**Comment by magicvince** [comment]
On debian I must added 

python3-pyqt5
pyqt5-dev-tools
qttools5dev

to compil and install.

Every thing seems to be ok, but when launch raysession 12.2 by the menu, nothing happen and if I'm using the command line, I've go a message telling me I had no permission

/usr/local/bin/raysession: ligne 4: /usr/local/share/raysession/src/bin/raysession: Permission non accordée

**Comment by Houston4444** [comment]
Hi @magicvince !
I have no idea on what happens, Could you please give the output of the following command:
`ls -l /usr/local/share/raysession/src/bin|grep raysession`

**Comment by magicvince** [comment]
When I install :
` raysession
/usr/local/bin/raysession: ligne 4: /usr/local/share/raysession/src/bin/raysession: Permission non accordée
/usr/local/bin/raysession: ligne 4 : exec: /usr/local/share/raysession/src/bin/raysession : impossible d'exécuter : Permission non accordée
`
And if I try to launch raysession without installation : 

`./src/bin/raysession 
Traceback (most recent call last):
  File "./src/bin/raysession", line 12, in <module>
    from gui_tools import ArgParser, CommandLineArgs, init_gui_tools, get_code_root
  File "/home/magicvince/Téléchargements/RaySession-0.12.2/src/gui/gui_tools.py", line 8, in <module>
    import ray
  File "/home/magicvince/Téléchargements/RaySession-0.12.2/src/gui/ray.py", line 4, in <module>
    import liblo
ModuleNotFoundError: No module named 'liblo'`

**Comment by magicvince** [comment]
So trying to install manually ubuntu raysession 0.8.3.deb I discover one dependancy is missing : python3-liblo.

After installation of this lib, i can make install the 0.12.2 version of RaySession (And now I can understand the error message "No module named 'liblo' " :) Thanks for your work

**Comment by Houston4444** [comment]
Hi @magicvince .
It's true, but all of theses are present in the install.md documentation : https://github.com/Houston4444/RaySession/blob/master/INSTALL.md .

**Comment by magicvince** [comment]
You're right, I'm so confuse :confused:
