### ISSUE TITLE
Unclean handling of "no space left on device"

### ISSUE THREAD

**Issue by strk** [Houston4444/RaySession#167]
I filled up my disk but wasn't easy to tell why RaySession failed to bring up a graph. Only when I've started from commandline I could see the problem:
```
$ raysession
[ray-daemon]GUI connected at osc.udp://c19:10437/
[ray-daemon]URL : osc.udp://192.168.1.30:16196/
[ray-daemon]      osc.udp://c19:16196/
[ray-daemon]ROOT: /home/strk/nextCloud/sandro/Studio/RaySessions
Calling appendChild() on a null node does nothing.
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/share/raysession/src/bin/ray-jackpatch_to_osc", line 595, in <module>
    main_process()
  File "/usr/local/share/raysession/src/bin/ray-jackpatch_to_osc", line 579, in main_process
    main_object = MainObject(daemon_port, gui_url)
  File "/usr/local/share/raysession/src/bin/ray-jackpatch_to_osc", line 137, in __init__
    self.write_existence_file()
  File "/usr/local/share/raysession/src/bin/ray-jackpatch_to_osc", line 169, in write_existence_file
    file.close()
OSError: [Errno 28] No space left on device
AttributeError: 'OscJackPatch' object has no attribute 'free'
Exception ignored in: 'liblo.Server.__dealloc__'
AttributeError: 'OscJackPatch' object has no attribute 'free'
```

It would be nice if some error could be printed with a popup or something :)

This was happening with raysession reporting `0.13.1` from `raysession --version`. I think I built it myself but dunno how to have the executable print the commit hash of it.

**Comment by Houston4444** [comment]
Ohh, quite annoying to do because it needs a new OSC message (ray-jackpatch_to_osc is another process), but doable sure. I think there is no message too if there is no space left at session creation too.
