### ISSUE TITLE
ImportError: cannot import name 'ChildDialog' from partially initialized module 'child_dialogs'

### ISSUE THREAD

**Issue by dromer** [Houston4444/RaySession#183]
I just upgraded my Debian 11 machine to 12 and am no longer able to launch raysession.

Then I tried rebuilding from latest source, but still get the same result:

```
dreamer@auditorium:~$ raysession 
Traceback (most recent call last):
  File "/usr/local/share/raysession/src/bin/raysession", line 15, in <module>
    from gui_session import SignaledSession
  File "/usr/local/share/raysession/src/gui/gui_session.py", line 6, in <module>
    from client_properties_dialog import NsmClientPropertiesDialog
  File "/usr/local/share/raysession/src/gui/client_properties_dialog.py", line 12, in <module>
    from child_dialogs import ChildDialog
  File "/usr/local/share/raysession/src/gui/child_dialogs.py", line 22, in <module>
    import ui.new_session
  File "/usr/local/share/raysession/src/gui/ui/__init__.py", line 1, in <module>
    from . import (
  File "/usr/local/share/raysession/src/gui/ui/raysession.py", line 712, in <module>
    from list_widget_clients import ListWidgetClients
  File "/usr/local/share/raysession/src/gui/list_widget_clients.py", line 11, in <module>
    import snapshots_dialog
  File "/usr/local/share/raysession/src/gui/snapshots_dialog.py", line 5, in <module>
    from child_dialogs import ChildDialog
ImportError: cannot import name 'ChildDialog' from partially initialized module 'child_dialogs' (most likely due to a circular import) (/usr/local/share/raysession/src/gui/child_dialogs.py)
```

**Comment by Houston4444** [comment]
Hmm, I have no src/gui/ui/__init__.py file. You may have it because it was probably used before (I can't remember). Try to remove this file.

**Comment by dromer** [comment]
Odd stuff, I see it there in my local copy of the repo.

Rebuilt it from a fresh clone and now it works!

</ignore>
