### ISSUE TITLE
Linuxsampler breakes RaySession

### ISSUE THREAD

**Issue by luciorgomes** [Houston4444/RaySession#196]
When I load a sample in Linuxsampler using jack connection (with QSampler or Konfyt) RaySession is killed with the error reproduced bellow.
Ps.: it hapens with Patchance too.

`[luciorg@lucio-dellg155530 ~]$ raysession 
[ray-daemon]GUI connected at osc.udp://lucio-dellg155530:12484/
[ray-daemon]URL : osc.udp://192.168.100.112:16187/
[ray-daemon]      osc.udp://lucio-dellg155530:16187/
[ray-daemon]ROOT: /home/luciorg/Ray Sessions
Traceback (most recent call last):
  File "/usr/share/raysession/src/gui/patchbay/patchbay_manager.py", line 906, in _delayed_orders_timeout
    group_id = oq.func(*oq.args, **oq.kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/raysession/src/gui/patchbay/patchbay_manager.py", line 594, in add_port
    group.check_for_portgroup_on_last_port()
  File "/usr/share/raysession/src/gui/patchbay/base_elements.py", line 1282, in check_for_portgroup_on_last_port
    other_port = self.stereo_detection(last_port)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/raysession/src/gui/patchbay/base_elements.py", line 1182, in stereo_detection
    while base_port[-1].isdigit():
          ~~~~~~~~~^^^^
IndexError: string index out of range
Abortado (imagem do núcleo gravada)
`
`[luciorg@lucio-dellg155530 ~]$ patchance
Traceback (most recent call last):
  File "/usr/share/patchance/src/patchbay/patchbay_manager.py", line 961, in _delayed_orders_timeout
    group_id = oq.func(*oq.args, **oq.kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/patchance/src/patchbay/patchbay_manager.py", line 640, in add_port
    group.check_for_portgroup_on_last_port()
  File "/usr/share/patchance/src/patchbay/base_elements.py", line 1295, in check_for_portgroup_on_last_port
    other_port = self.stereo_detection(last_port)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/patchance/src/patchbay/base_elements.py", line 1195, in stereo_detection
    while base_port[-1].isdigit():
          ~~~~~~~~~^^^^
IndexError: string index out of range
Abortado (imagem do núcleo gravada)
`

**Comment by Houston4444** [comment]
Linuxsampler seems to add JACK ports whose names contains only digits. Indeed, this case was not planned.
I just pushed a fix, I did not try, but it should works.
Please update RaySession and/or Patchance and try !

**Comment by luzpaz** [comment]
@luciorgomes can you still reproduce ?
