### ISSUE TITLE
RaySession segfault on Fedora 39

### ISSUE THREAD

**Issue by ycollet** [Houston4444/RaySession#220]
RaySession segfault on Fedora 39.
Yesterday everything was working fine and today, Ray Session is segfaulting.
So, certainly related to an update ... No yet able to identify the problem.

**Comment by ycollet** [comment]
So, it looks like it's a python 3.12 problem. Not related to raysession:
```
Program received signal SIGSEGV, Segmentation fault.
_PyDict_Next (op=0x0, ppos=0x7ffd8c5367e0, pkey=0x7ffd8c5367e8, pvalue=0x7ffd8c5367f0, phash=0x0) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/dictobject.c:2114
Downloading source file /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/dictobject.c
2114        if (!PyDict_Check(op))                                                                                                                                                                            
Missing separate debuginfos, use: dnf debuginfo-install python3-3.12.1-2.fc39.x86_64
(gdb) where
#0  _PyDict_Next (op=0x0, ppos=0x7ffd8c5367e0, pkey=0x7ffd8c5367e8, pvalue=0x7ffd8c5367f0, phash=0x0) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/dictobject.c:2114
#1  0x00007f7bd8e2214e in trawl_type (pprops=..., psigs=..., builder=..., qo=0x56119bed2530, pytype=0x7f7bebbd3d40 <PyBaseObject_Type>) at ../../qpy/QtCore/qpycore_types.cpp:392
#2  trawl_hierarchy (pytype=pytype@entry=0x7f7bebbd3d40 <PyBaseObject_Type>, qo=qo@entry=0x56119bed2530, builder=..., psigs=..., pprops=...) at ../../qpy/QtCore/qpycore_types.cpp:341
#3  0x00007f7bd8e22701 in trawl_hierarchy (pytype=pytype@entry=0x56119bfc7cd0, qo=qo@entry=0x56119bed2530, builder=..., psigs=..., pprops=...) at ../../qpy/QtCore/qpycore_types.cpp:374
#4  0x00007f7bd8e22701 in trawl_hierarchy (pytype=pytype@entry=0x56119c1cf300, qo=qo@entry=0x56119bed2530, builder=..., psigs=..., pprops=...) at ../../qpy/QtCore/qpycore_types.cpp:374
#5  0x00007f7bd8e241c6 in create_dynamic_metaobject (wt=0x56119c1cf300) at ../../qpy/QtCore/qpycore_types.cpp:117
#6  qpycore_new_user_type_handler (wt=0x56119c1cf300) at ../../qpy/QtCore/qpycore_types.cpp:70
#7  0x00007f7bdaf60a62 in sipWrapperType_init (self=0x56119c1cf300, args=<optimized out>, kwds=<optimized out>) at /usr/src/debug/python-pyqt5-sip-12.13.0-1.fc39.x86_64/siplib.c:9865
#8  0x00007f7beb7f73ab in type_call (type=<optimized out>, type@entry=0x7f7bdaf6d840 <sipWrapperType_Type>, args=args@entry=0x7f7bd7b54dc0, kwds=kwds@entry=0x0)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/typeobject.c:1673
#9  0x00007f7beb7f7156 in _PyObject_MakeTpCall (tstate=0x7f7bebc4e668 <_PyRuntime+459656>, callable=0x7f7bdaf6d840 <sipWrapperType_Type>, args=0x7ffd8c536bc0, nargs=3, keywords=0x0)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/call.c:240
#10 0x00007f7beb88c7eb in builtin___build_class__ (self=<optimized out>, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/bltinmodule.c:208
#11 0x00007f7beb80b08c in cfunction_vectorcall_FASTCALL_KEYWORDS (func=0x7f7bddd95990, args=0x7f7bebdd2c10, nargsf=<optimized out>, kwnames=0x0)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Include/cpython/methodobject.h:50
#12 0x00007f7beb80abfc in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=9223372036854775812, args=0x7f7bebdd2c10, callable=0x7f7bddd95990, tstate=0x7f7bebc4e668 <_PyRuntime+459656>)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Include/internal/pycore_call.h:92
#13 PyObject_Vectorcall (callable=0x7f7bddd95990, args=0x7f7bebdd2c10, nargsf=9223372036854775812, kwnames=0x0) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/call.c:325
#14 0x00007f7beb70f75a in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7f7bebdd2bb8, throwflag=<optimized out>) at Python/bytecodes.c:2706
#15 0x00007f7beb88b196 in PyEval_EvalCode (co=0x7f7bd7b2e740, globals=<optimized out>, locals=0x7f7bd7e276c0) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/ceval.c:578
#16 0x00007f7beb8a61dc in builtin_exec_impl (module=<optimized out>, closure=<optimized out>, locals=0x7f7bd7e276c0, globals=0x7f7bd7e276c0, source=0x7f7bd7b2e740)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/bltinmodule.c:1096
#17 builtin_exec (module=<optimized out>, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/clinic/bltinmodule.c.h:586
#18 0x00007f7beb80b08c in cfunction_vectorcall_FASTCALL_KEYWORDS (func=0x7f7bddd95e40, args=0x7f7bd7b54a98, nargsf=<optimized out>, kwnames=0x0)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Include/cpython/methodobject.h:50
#19 0x00007f7beb71017b in PyCFunction_Call (kwargs=0x7f7bd7b42c40, args=0x7f7bd7b54a80, callable=0x7f7bddd95e40) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/call.c:387
#20 _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7f7bebdd2b30, throwflag=<optimized out>) at Python/bytecodes.c:3254
#21 0x00007f7beb812cdb in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=2, args=0x7ffd8c5371b0, callable=0x7f7bddda4040, tstate=0x7f7bebc4e668 <_PyRuntime+459656>)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Include/internal/pycore_call.h:92
#22 object_vacall (tstate=tstate@entry=0x7f7bebc4e668 <_PyRuntime+459656>, base=<optimized out>, callable=0x7f7bddda4040, vargs=0x7ffd8c537240)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/call.c:850
#23 0x00007f7beb834eca in PyObject_CallMethodObjArgs (obj=<optimized out>, name=<optimized out>) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/call.c:911
#24 0x00007f7beb8347d2 in import_find_and_load (abs_name=0x7f7bd7e27530, tstate=0x7f7bebc4e668 <_PyRuntime+459656>) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/import.c:2779
#25 PyImport_ImportModuleLevelObject (name=0x7f7bd7e27530, globals=<optimized out>, locals=<optimized out>, fromlist=0x7f7bd7e14680, level=0)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/import.c:2862
#26 0x00007f7beb7157b7 in import_name (level=0x7f7bebbdefa8 <_PyRuntime+3272>, fromlist=0x7f7bd7e14680, name=0x7f7bd7e27530, frame=0x7f7bebdd2848, tstate=<optimized out>)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/ceval.c:2484
#27 _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7f7bebdd2848, throwflag=<optimized out>) at Python/bytecodes.c:2135
#28 0x00007f7beb88b196 in PyEval_EvalCode (co=0x7f7bd7fb0ed0, globals=<optimized out>, locals=0x7f7bd8bf7c00) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/ceval.c:578
#29 0x00007f7beb8a61dc in builtin_exec_impl (module=<optimized out>, closure=<optimized out>, locals=0x7f7bd8bf7c00, globals=0x7f7bd8bf7c00, source=0x7f7bd7fb0ed0)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/bltinmodule.c:1096
#30 builtin_exec (module=<optimized out>, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/clinic/bltinmodule.c.h:586
#31 0x00007f7beb80b08c in cfunction_vectorcall_FASTCALL_KEYWORDS (func=0x7f7bddd95e40, args=0x7f7bd7e24398, nargsf=<optimized out>, kwnames=0x0)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Include/cpython/methodobject.h:50
#32 0x00007f7beb71017b in PyCFunction_Call (kwargs=0x7f7bd7e145c0, args=0x7f7bd7e24380, callable=0x7f7bddd95e40) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/call.c:387
#33 _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7f7bebdd27c0, throwflag=<optimized out>) at Python/bytecodes.c:3254
#34 0x00007f7beb812cdb in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=2, args=0x7ffd8c5378e0, callable=0x7f7bddda4040, tstate=0x7f7bebc4e668 <_PyRuntime+459656>)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Include/internal/pycore_call.h:92
--Type <RET> for more, q to quit, c to continue without paging--
#35 object_vacall (tstate=tstate@entry=0x7f7bebc4e668 <_PyRuntime+459656>, base=<optimized out>, callable=0x7f7bddda4040, vargs=0x7ffd8c537970)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/call.c:850
#36 0x00007f7beb834eca in PyObject_CallMethodObjArgs (obj=<optimized out>, name=<optimized out>) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/call.c:911
#37 0x00007f7beb8347d2 in import_find_and_load (abs_name=0x7f7bddabf970, tstate=0x7f7bebc4e668 <_PyRuntime+459656>) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/import.c:2779
#38 PyImport_ImportModuleLevelObject (name=0x7f7bddabf970, globals=<optimized out>, locals=<optimized out>, fromlist=0x7f7bddacd780, level=0)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/import.c:2862
#39 0x00007f7beb7157b7 in import_name (level=0x7f7bebbdefa8 <_PyRuntime+3272>, fromlist=0x7f7bddacd780, name=0x7f7bddabf970, frame=0x7f7bebdd24b8, tstate=<optimized out>)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/ceval.c:2484
#40 _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7f7bebdd24b8, throwflag=<optimized out>) at Python/bytecodes.c:2135
#41 0x00007f7beb88b196 in PyEval_EvalCode (co=0x56119bcd8fd0, globals=<optimized out>, locals=0x7f7bdddfa140) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/ceval.c:578
#42 0x00007f7beb8a61dc in builtin_exec_impl (module=<optimized out>, closure=<optimized out>, locals=0x7f7bdddfa140, globals=0x7f7bdddfa140, source=0x56119bcd8fd0)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/bltinmodule.c:1096
#43 builtin_exec (module=<optimized out>, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/clinic/bltinmodule.c.h:586
#44 0x00007f7beb80b08c in cfunction_vectorcall_FASTCALL_KEYWORDS (func=0x7f7bddd95e40, args=0x7f7bebdd2490, nargsf=<optimized out>, kwnames=0x0)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Include/cpython/methodobject.h:50
#45 0x00007f7beb80abfc in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=9223372036854775809, args=0x7f7bebdd2490, callable=0x7f7bddd95e40, tstate=0x7f7bebc4e668 <_PyRuntime+459656>)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Include/internal/pycore_call.h:92
#46 PyObject_Vectorcall (callable=0x7f7bddd95e40, args=0x7f7bebdd2490, nargsf=9223372036854775809, kwnames=0x0) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/call.c:325
#47 0x00007f7beb70f75a in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7f7bebdd2438, throwflag=<optimized out>) at Python/bytecodes.c:2706
#48 0x00007f7beb88b196 in PyEval_EvalCode (co=0x7f7bdda26b50, globals=<optimized out>, locals=0x7f7bdddfa140) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/ceval.c:578
#49 0x00007f7beb8a61dc in builtin_exec_impl (module=<optimized out>, closure=<optimized out>, locals=0x7f7bdddfa140, globals=0x7f7bdddfa140, source=0x7f7bdda26b50)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/bltinmodule.c:1096
#50 builtin_exec (module=<optimized out>, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/clinic/bltinmodule.c.h:586
#51 0x00007f7beb710bfa in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7f7bebdd23a0, throwflag=<optimized out>)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Include/cpython/methodobject.h:50
#52 0x00007f7beb88b196 in PyEval_EvalCode (co=0x56119badfff0, globals=<optimized out>, locals=0x7f7bdddfa140) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/ceval.c:578
#53 0x00007f7beb8a61dc in builtin_exec_impl (module=<optimized out>, closure=<optimized out>, locals=0x7f7bdddfa140, globals=0x7f7bdddfa140, source=0x56119badfff0)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/bltinmodule.c:1096
#54 builtin_exec (module=<optimized out>, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/clinic/bltinmodule.c.h:586
#55 0x00007f7beb80b08c in cfunction_vectorcall_FASTCALL_KEYWORDS (func=0x7f7bddd95e40, args=0x7f7bebdd2180, nargsf=<optimized out>, kwnames=0x0)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Include/cpython/methodobject.h:50
#56 0x00007f7beb80abfc in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=9223372036854775810, args=0x7f7bebdd2180, callable=0x7f7bddd95e40, tstate=0x7f7bebc4e668 <_PyRuntime+459656>)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Include/internal/pycore_call.h:92
#57 PyObject_Vectorcall (callable=0x7f7bddd95e40, args=0x7f7bebdd2180, nargsf=9223372036854775810, kwnames=0x0) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/call.c:325
#58 0x00007f7beb70f75a in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7f7bebdd20d8, throwflag=<optimized out>) at Python/bytecodes.c:2706
#59 0x00007f7beb8b9ced in pymain_run_module (modname=<optimized out>, set_argv0=set_argv0@entry=1) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Modules/main.c:300
#60 0x00007f7beb8b9719 in pymain_run_python (exitcode=0x7ffd8c5386b4) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Modules/main.c:623
#61 Py_RunMain () at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Modules/main.c:709
#62 0x00007f7beb874f5c in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Modules/main.c:763
#63 0x00007f7beb44614a in __libc_start_call_main (main=main@entry=0x56119b612160 <main>, argc=argc@entry=4, argv=argv@entry=0x7ffd8c538948) at ../sysdeps/nptl/libc_start_call_main.h:58
#64 0x00007f7beb44620b in __libc_start_main_impl (main=0x56119b612160 <main>, argc=4, argv=0x7ffd8c538948, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd8c538938)
    at ../csu/libc-start.c:360
#65 0x000056119b612095 in _start ()
```

**Comment by ycollet** [comment]
It was a problem of partly installed qt5 update.
The part of the Qt5 update which came from rpmfusion was partly installed and blocked by the fedorq qt5 update which only came today. Now ray session works again.
I close the ticket.
