### ISSUE TITLE
raysession: nsmClientIs_clean(): osc_server_thread.py:250:nsmClientIs_clean:AttributeError: 'Signaler' object has no attribute 'server_save_from_client'

### ISSUE THREAD

**Issue by eeickmeyer** [Houston4444/RaySession#50]
This appears on the RedHat Bugzilla Bug Tracker: https://bugzilla.redhat.com/show_bug.cgi?id=1836548

```
Description of problem:
Saving in Ardour

Version-Release number of selected component:
raysession-0.8.3-1.fc32

Additional info:
reporter:       libreport-2.12.0
cgroup:         0::/user.slice/user-1002.slice/user@1002.service/gnome-launched-raysession.desktop-444195.scope
cmdline:        /usr/bin/python3 -u /usr/share/raysession/src/bin/ray-daemon --gui-url osc.udp://localhost:10900/ --osc-port 16187 --session-root '/home/bruno2/Ray Sessions'
crash_function: nsmClientIs_clean
exception_type: AttributeError
executable:     /usr/share/raysession/src/bin/ray-daemon
interpreter:    python3-3.8.2-2.fc32.x86_64
kernel:         5.6.12-300.fc32.x86_64
runlevel:       N 5
type:           Python3
uid:            1002

Truncated backtrace:
osc_server_thread.py:250:nsmClientIs_clean:AttributeError: 'Signaler' object has no attribute 'server_save_from_client'

Traceback (most recent call last):
  File "src/liblo.pyx", line 55, in liblo._weakref_method.__call__
  File "/usr/share/raysession/src/daemon/osc_server_thread.py", line 38, in wrapper
    response = func(*args[:-1], **kwargs)
  File "/usr/share/raysession/src/daemon/osc_server_thread.py", line 250, in nsmClientIs_clean
    signaler.server_save_from_client.emit(path, args,
AttributeError: 'Signaler' object has no attribute 'server_save_from_client'

Local variables in innermost frame:
self: <osc_server_thread.OscServerThread object at 0x7feab0bc0810>
path: '/nsm/client/is_clean'
args: []
types: ''
src_addr: <liblo.Address object at 0x7feab0a28ed0>
client: <client.Client object at 0x7feab0a2caf0>
```

**Comment by Houston4444** [comment]
Hi, thanks for the issue report.
Save from client option has been removed in master branch, because it was borderline regarding the NSM API respect.
To save session, affect a global shortcut (for example Ctrl+Meta+S) to the command `ray_control save`.
I tag here @BrunoVernay because he report the issue to redhat bugzilla.
