### ISSUE TITLE
Latest version seems broken?

### ISSUE THREAD

**Issue by gauderbock** [Houston4444/RaySession#75]
Hi, I've just upgraded to the latest version and it's broken the app. When loading a session, I get this:

`qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
[ray-daemon]GUI connected at osc.udp://lappy:12386/
[ray-daemon]URL : osc.udp://192.168.1.234:16187/
[ray-daemon]      osc.udp://lappy:16187/
[ray-daemon]ROOT: /home/me/Ray Sessions
[ray-daemon]Attempting to open /home/me/Ray Sessions/default
Traceback (most recent call last):
  File "/usr/local/share/raysession/src/daemon/session_signaled.py", line 102, in oscReceive
    function(path, args, src_addr)
  File "/usr/local/share/raysession/src/daemon/session_signaled.py", line 47, in wrapper
    sess.nextFunction()
  File "/usr/local/share/raysession/src/daemon/session.py", line 618, in nextFunction
    next_function(*arguments)
  File "/usr/local/share/raysession/src/daemon/session.py", line 794, in save
    self.nextFunction()
  File "/usr/local/share/raysession/src/daemon/session.py", line 618, in nextFunction
    next_function(*arguments)
  File "/usr/local/share/raysession/src/daemon/session.py", line 1034, in closeNoSaveClients
    ray.WaitFor.QUIT)
  File "/usr/local/share/raysession/src/daemon/session.py", line 513, in waitAndGoTo
    follow()
  File "/usr/local/share/raysession/src/daemon/session.py", line 1053, in closeNoSaveClients_substep1
    self.waitAndGoTo(120000, self.nextFunction, ray.WaitFor.QUIT, True)
  File "/usr/local/share/raysession/src/daemon/session.py", line 513, in waitAndGoTo
    follow()
  File "/usr/local/share/raysession/src/daemon/session.py", line 618, in nextFunction
    next_function(*arguments)
  File "/usr/local/share/raysession/src/daemon/session.py", line 959, in snapshot
    self.nextFunction()
  File "/usr/local/share/raysession/src/daemon/session.py", line 618, in nextFunction
    next_function(*arguments)
  File "/usr/local/share/raysession/src/daemon/session.py", line 1576, in preload
    client.readXmlProperties(cx)
  File "/usr/local/share/raysession/src/daemon/client.py", line 190, in readXmlProperties
    self.updateInfosFromDesktopFile()
  File "/usr/local/share/raysession/src/daemon/client.py", line 1390, in updateInfosFromDesktopFile
    % desk_path):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/share/raysession/data/share/applications/'

`

Previous installs were working fine, and I've tried removing the ray stuff in /usr/local/bin and /usr/local/share before reinstalling, it still doesn't work...

Thanks.

**Comment by Houston4444** [comment]
Hi.
Thanks for the report.
Sorry I did not test to install this after last commit.
It should be fixed now.

**Comment by gauderbock** [comment]
Yes, thanks, all's well again.
