### ISSUE TITLE
How to distribute session ?

### ISSUE THREAD

**Issue by newlaurent62** [Houston4444/RaySession#79]
Hello,

I'm facing a use case where several machines would be better than only one.

I will have at least two machines may be three. I did not test this solution, it's only an idea by now.

I know that NSM is capable of distributed session but i have no idea how to get this running.
As RaySession is NSM compatible it should also be capable of distrbuted session, isn't it ?

So how does this work ? How do i distribute the clients through the hosts ? Where do i declare the host used ...

BR,
Laurent

**Comment by Houston4444** [comment]
Hi.
It works in a different way on RaySession than in NSM.
Simply add the template "Network Session" from the Application Dialog and follow the instructions.

**Comment by newlaurent62** [comment]
Ok i follow the instructions.

I have know a daemon running on host B declared in master session on hast A.

When i click on GUI icon of Network Session, a RaySession App pops up main options are disabled ? What do i do now ?

![image](https://user-images.githubusercontent.com/10225394/85942407-5e976800-b929-11ea-8f3d-2384ea14b84f.png)

**Comment by Houston4444** [comment]
Aïe, this is a bug. Session frame should be enabled.
I can't reproduce it.
Are you sure to have exactly the same version on both computers ?
Is there any error message in raysession or in distant ray-deamon ?
It's also very strange to have no label on "Session Réseau" status bar.

**Comment by newlaurent62** [comment]
Sorry i forgot to install branch master on the host B.

I'll try and report.

**Comment by newlaurent62** [comment]
Thanks for the tips !

I installed same RS version on both side and now i can access to all options on the slave session.

When i try to add a client  executable which is "obs" and NSM protocol unchecked, nothing happen on RS slave GUI host A and i get an error on ray-daemon side on host B:

```
Traceback (most recent call last):
  File "/usr/local/share/raysession/src/daemon/session_signaled.py", line 102, in oscReceive
    function(path, args, src_addr)
  File "/usr/local/share/raysession/src/daemon/session_signaled.py", line 826, in _ray_session_add_executable
    if self.addClient(client):
  File "/usr/local/share/raysession/src/daemon/session.py", line 360, in addClient
    client.updateInfosFromDesktopFile()
  File "/usr/local/share/raysession/src/daemon/client.py", line 1389, in updateInfosFromDesktopFile
    for desk_file in os.listdir("%s/share/applications/"
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/home/jamulusos/.local/share/applications/'
```
The obs deskop path on host B is:
`/usr/share/applications/com.obsproject.Studio.desktop`

also `/home/jamulusos/.local/share/applications` does not exist on host B.

When i type obs in a terminal on host B, the application startup even if it complains about graphic drivers ...

I tried successfully adding guitarix executable as Hack.

**Comment by Houston4444** [comment]
It was a stupid bug, code was trying to list a folder without check if that folder exists. It's fixed. Thanks

**Comment by newlaurent62** [comment]
Ok Thanks, it works.

**Comment by newlaurent62** [comment]
> It's also very strange to have no label on "Session Réseau" status bar.

Indeed, if a reminder on network session could be added this would be very useful. Currently, there's no GUI elements indicating that i am running a distributed session.

**Comment by Houston4444** [comment]
Ah, I was thinking that user would easily recognize that there is no toolbar in a slave session (no possibility to open or create a session).
So, If you didn't notice this, I was probably wrong.

**Comment by newlaurent62** [comment]
It would be useful to remember the IP / hostname of the machine and the port

**Comment by Houston4444** [comment]
> It would be useful to remember the IP / hostname of the machine and the port.
Something like : "RaySession - {session name} ( {hostname or IP}:{port} )"

I am not sure to understand, what you want would be a label on the slave session GUI ? Its window title ? window title is a good idea, quite fast to write.

**Comment by newlaurent62** [comment]
Yes, I would like the window title to be set with something like:  "RaySession - {session name} ( {hostname or IP}:{port} )"

**Comment by newlaurent62** [comment]
But if you want to put (hostname:port) on Network Session label in master session, it would be useful too !

**Comment by Houston4444** [comment]
> But if you want to put (hostname:port) on Network Session label in master session, it would be useful too !

Later, in tooltip.
