### ISSUE TITLE
Last install from git fails

### ISSUE THREAD

**Issue by moonshaadow** [Houston4444/RaySession#86]
Hi there.
```
~$ raysession
QApplication: invalid style override passed, ignoring it.
qt.svg: Cannot open file ':/scalable/raysession.svg', because: No such file or directory
qt.svg: Cannot open file ':/scalable/raysession.svg', because: No such file or directory
Traceback (most recent call last):
  File "/usr/local/share/raysession/src/bin/raysession", line 87, in <module>
    session = SignaledSession()
  File "/usr/local/share/raysession/src/gui/gui_session.py", line 145, in __init__
    Session.__init__(self)
  File "/usr/local/share/raysession/src/gui/gui_session.py", line 51, in __init__
    self._main_win = MainWindow(self)
  File "/usr/local/share/raysession/src/gui/main_window.py", line 28, in __init__
    self.ui = ui_raysession.Ui_MainWindow()
AttributeError: module 'ui_raysession' has no attribute 'Ui_MainWindow'

```

Ubuntu studio 18.04, xfce

**Comment by Houston4444** [comment]
Hi. I suspect you forgot to type `make` before `sudo make install`.

**Comment by moonshaadow** [comment]
No, make has been done with no error. As suggested, `sudo make uninstall` has been done too.

**Comment by moonshaadow** [comment]
As I said in #61 , I use `make -qt` , because regular way doesn't work for me. All previous versions have been successfully installed by this way.

**Comment by Houston4444** [comment]
this `make -qt` option is strange.
what gives followings commands:
`which lrelease`
`which lrelease-qt4`
`which lrelease-qt5`

**Comment by moonshaadow** [comment]
> what gives followings commands:
> which lrelease
> which lrelease-qt4
> which lrelease-qt5

Nothing at all :-/

But I'm able to build doing the following : `make LRELEASE=lrelease-qt5` then `make -qt` : 
```
$ make LRELEASE=lrelease-qt5
pyrcc5 resources/resources.qrc -o src/gui/resources_rc.py
pyuic5 resources/ui/abort_copy.ui -o src/gui/ui_abort_copy.py
pyuic5 resources/ui/abort_session.ui -o src/gui/ui_abort_session.py
pyuic5 resources/ui/about_raysession.ui -o src/gui/ui_about_raysession.py
pyuic5 resources/ui/add_application.ui -o src/gui/ui_add_application.py
pyuic5 resources/ui/client_properties.ui -o src/gui/ui_client_properties.py
pyuic5 resources/ui/client_slot.ui -o src/gui/ui_client_slot.py
pyuic5 resources/ui/client_trash.ui -o src/gui/ui_client_trash.py
pyuic5 resources/ui/donations.ui -o src/gui/ui_donations.py
pyuic5 resources/ui/daemon_url.ui -o src/gui/ui_daemon_url.py
pyuic5 resources/ui/error_dialog.ui -o src/gui/ui_error_dialog.py
pyuic5 resources/ui/jack_config_info.ui -o src/gui/ui_jack_config_info.py
pyuic5 resources/ui/list_snapshots.ui -o src/gui/ui_list_snapshots.py
pyuic5 resources/ui/new_executable.ui -o src/gui/ui_new_executable.py
pyuic5 resources/ui/new_session.ui -o src/gui/ui_new_session.py
pyuic5 resources/ui/nsm_properties.ui -o src/gui/ui_nsm_properties.py
pyuic5 resources/ui/ray_hack_copy.ui -o src/gui/ui_ray_hack_copy.py
pyuic5 resources/ui/nsm_open_info.ui -o src/gui/ui_nsm_open_info.py
pyuic5 resources/ui/open_session.ui -o src/gui/ui_open_session.py
pyuic5 resources/ui/quit_app.ui -o src/gui/ui_quit_app.py
pyuic5 resources/ui/ray_hack_properties.ui -o src/gui/ui_ray_hack_properties.py
pyuic5 resources/ui/raysession.ui -o src/gui/ui_raysession.py
pyuic5 resources/ui/remove_template.ui -o src/gui/ui_remove_template.py
pyuic5 resources/ui/save_template_session.ui -o src/gui/ui_save_template_session.py
pyuic5 resources/ui/session_scripts_info.ui -o src/gui/ui_session_scripts_info.py
pyuic5 resources/ui/script_info.ui -o src/gui/ui_script_info.py
pyuic5 resources/ui/script_user_action.ui -o src/gui/ui_script_user_action.py
pyuic5 resources/ui/snapshot_name.ui -o src/gui/ui_snapshot_name.py
pyuic5 resources/ui/snapshots_info.ui -o src/gui/ui_snapshots_info.py
pyuic5 resources/ui/snapshot_progress.ui -o src/gui/ui_snapshot_progress.py
pyuic5 resources/ui/stop_client.ui -o src/gui/ui_stop_client.py
pyuic5 resources/ui/stop_client_no_save.ui -o src/gui/ui_stop_client_no_save.py
pyuic5 resources/ui/template_slot.ui -o src/gui/ui_template_slot.py
pyuic5 resources/ui/waiting_close_user.ui -o src/gui/ui_waiting_close_user.py
pyuic5 resources/ui/proxy_copy.ui -o src/clients/proxy/ui_proxy_copy.py
pyuic5 resources/ui/proxy_gui.ui -o src/clients/proxy/ui_proxy_gui.py
lrelease-qt5 locale/raysession_fr_FR.ts -qm locale/raysession_fr_FR.qm
make: lrelease-qt5: Command not found
Makefile:90: recipe for target 'locale/raysession_fr_FR.qm' failed
make: *** [locale/raysession_fr_FR.qm] Error 127
studio@studio-Dell:~/Bureau/RaySession$ make -qt
touch ray_proxy
touch locale/raysession_fr_FR.qm
touch locale/raysession_en_US.qm

```

**Comment by Houston4444** [comment]
lrelease is only needed for translations, I don't think it prevents RaySession to work, even if it make make fails.
you can try to install qt4-linguist-tools package.
I really don't see the goal of `make -qt`, what happens if you do not execute this ? Why could it be needed ?

**Comment by moonshaadow** [comment]
Ok, you're absolutely right. I've got a translation related error doing `make` alone, solved with qt4-linguist-tools. So now I've got a beautiful french RS ;-) 
Merci beaucoup!
I own you a few beers !

Maybe you could add qt4-linguist-tools package as an optional dependency, in order to avoid noobs like me to panic seeing error :-)

I close this one.
